image: docker:latest

stages:
  - test
  - build
  - deploy-dev

test:
  stage: test
  image: alpine
  script:
      # Install alpine-sdk
      - apk add --update alpine-sdk
  
      # Install py-pip for some yarn dependencies
      - apk add --update py-pip 
      - pip install -U pip

      # Install node/npm/yarn and build
      - apk add --update nodejs nodejs-npm
      - apk add --update yarn
      - cd app 
      - yarn
      
      - echo "FILES"
      - ls
      
      # Create test
      - echo "TEST START"
      - yarn test
      - echo "TEST COMPLETE" 
  artifacts:
    paths:
      - app/node_modules/
    expire_in: 60 mins

build:
  stage: build
  image: alpine
  dependencies:
    - test
  script:
      # Install node/npm and build
      - apk add --update nodejs nodejs-npm
      - apk add --update yarn

      # create-react-app option GENERATE_SOURCEMAP=false can help with OOM issues on build for large apps
      - export GENERATE_SOURCEMAP=false
      
      # Create build
      - cd app
      - echo "BUILD START"
      - yarn build
      - echo "BUILD COMPLETE"
  artifacts:
    paths:
      - app/build/
    expire_in: 60 mins
  only:
    - master
    - develop

deploy-dev:
  stage: deploy-dev
  image: python:3.7-alpine
  dependencies:
    - build
  script:
    # Configure environment variables injected by GitLab
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID       
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

    # Install awscli
    - export PATH=~/.local/bin:$PATH    
    - pip install awscli --upgrade --user

    # Install npm & serverless
    - apk add --update nodejs nodejs-npm
    - npm install -g serverless

    # Make sure serverless s3 plugin is installed
    - yarn

    # Configure serverless using injected environment variables for AWS IAM setup
    - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_ACCESS_KEY_SECRET --profile default
    
    # Sync build/ to s3 bucket and invalidate cache
    - serverless syncToS3
    - serverless invalidatCloudFrontCache

    - echo "DEPLOYMENT COMPLETE"
  environment:
    name: dev