stages:
  - test
  - build
  - deploy

test:
  image: node:10.19.0-buster
  stage: test
  script:   
    - cd app
    - yarn
    - yarn test
  artifacts:
    paths:
      - app/node_modules/
    expire_in: 10 mins

build:
  image: node:10.19.0-buster
  stage: build
  dependencies:
    - test
  script:
      - cd app
      - yarn build
  artifacts:
    paths:
      - app/build/
    expire_in: 20 mins
  only:
    - develop    
    - master

deploy:
  image: node:10.19.0-buster
  stage: deploy
  dependencies:
    - build  
  script:
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - npm install -g serverless
    - yarn
    - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_ACCESS_KEY_SECRET --profile default --overwrite
    - ./deploy_stack.sh $CI_COMMIT_REF_NAME
    - serverless syncToS3 -v --stage $CI_COMMIT_REF_NAME
    - serverless invalidateCloudFrontCache -v --stage $CI_COMMIT_REF_NAME
  environment:
    name: $CI_COMMIT_REF_NAME
  only:
    - develop
    - master